- name: install in local
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: local
      vars:
        course: "DevOps"
      ansible.builtin.debug:
      mes: "i m traning at course {{course}}"

    