- name: play variable
  hosts: local
  connection: local
  vars:
    firstame: "yashwanth"
    lastname: aarem
  tasks:
  - name: print variable
    ansible.builtin.debug:
     msg: "{{ firstame }}"
   