- name: promt variable
  hosts: local
  connection: local
  vars_promt:
  - name: place
    promt: where are you from
    private: true

  tasks:
  - name: promt
    ansible.builtin.debug:
      msg: "{{ place }}"