- name: prompt variable
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: where are you from
    private: false

  - name: password
    prompt: where are you going
    private: true

  tasks:
  - name: prompt
    ansible.builtin.debug:
      msg: "{{ username }} next {{ password }}"