- name: promt variable
  hosts: local
  connection: local
  vars:
  - name: city
    promt: where are you from
    private: true

  tasks:
  - name: promt
    ansible.builtin.debug:
      msg: "{{ city }}"